services:
  app:
    build:
      dockerfile: ./app/Dockerfile
      context: .
    ports:
      - "8501:8501"
    volumes:
      - ./app:/app
    depends_on:
      - ipfs
    networks:
      - tokenizart_network
  
  ipfs:
    image: ipfs/kubo:latest
    ports:
      - "8080:8080"
    volumes:
      - ipfs_data:/data/ipfs
    networks:
      - tokenizart_network

volumes:
  ipfs_data:
    driver: local

networks:
  tokenizart_network:
    driver: bridge